### ISSUE TITLE
Vagrant error when trying to mount filesystem

### ISSUE THREAD

**Issue by SamStonehouse** [renobit/vagrant-node-env#5] opened 2015-05-28 12:01 UTC
I get the following error 

```
==> default: /sbin/mount.vboxsf: mounting failed with the error
==> default: : No such file or directory
```

I've downloaded the repo as a zip and ran `vagrant up` as is

Any ideas?

**Comment by davidmyersdev** [comment] 2015-06-01 15:28
Could you give me your OS version and your Vagrant version?

**Comment by SamStonehouse** [comment] 2015-06-02 09:36
Not working on - 
Windows 7 64bit Enterprise Edition - Vagrant 1.7.2

Working on -
Windows 7 64bit Professional - Vagrant 1.6.5
Windows 7 64bit Professional - Vagrant 1.7.2 (Same system after updating vagrant)

**Comment by davidmyersdev** [comment] 2015-06-15 16:55
Sorry about the late reply to this. I've been incredibly swamped with work. I will try to take a look at this tonight and get back to you. Thanks for the heads up!

**Comment by SamStonehouse** [comment] 2015-06-25 19:56
I've run into this a few times now, restarting the host machine seems to fix it

**Comment by davidmyersdev** [comment] 2015-06-29 21:56
Can you also list your VirtualBox versions next to those OS/Vagrant versions? I'm not currently able to re-create this, but I did find a similar error message in the [Vagrant issues](https://github.com/mitchellh/vagrant/issues/1657). It looks like their issue was caused by VirtualBox and not Vagrant. 

I appreciate you keeping my attention on this!

**Comment by davidmyersdev** [comment] 2015-07-07 22:43
Closing this as I have no evidence to suggest this is a problem with my coding/configuration. As the previous comment states, this seems to be a VirtualBox issue instead.

**Closed as completed by davidmyersdev** 2015-07-07 22:43 UTC
Labels: bug
